name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash

jobs:
  rustfmt:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
        toolchain: stable
    - run: cargo fmt --all --check

  clippy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
        toolchain: stable
    - uses: actions-rs-plus/clippy-check@4f0f406361254011722b2da38ee8bf848e832bd3
      with:
          args: --all-features

  check:
    runs-on: ${{ matrix.os }}
    env:
      CARGO_PROFILE_DEV_DEBUG: 1
      CARGO_PROFILE_TEST_DEBUG: 1
      CARGO_INCREMENTAL: 0
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          rust: stable
        - os: macos-latest
          rust: stable
          other: x86_64-apple-ios
        - os: windows-latest
          rust: stable-msvc
        - os: windows-latest
          rust: beta-msvc
        - os: windows-latest
          rust: nightly-msvc
        - os: windows-latest
          rust: stable-gnu
    steps:
    - uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - run: cargo check --verbose
